model_params:
  name: 'BetaVAE'
  beta: 2
  in_channels: 3
  latent_dim: 10
  loss_type: 'H'
  max_capacity: 25
  Capacity_max_iter: 10000
  image_height: 64
  image_width: 64
  hidden_dims: [32, 64, 128, 256, 512]

exp_params:
  img_size: 64
  train_data_dir: "./data_train"
  val_data_dir: "./data_val"
  model_save_dir: "./best_model"
  batch_size: 256 # Better to have a square number
  learning_rate: 0.002
  weight_decay: 0.0
  scheduler_gamma: 0.6
  max_epochs: 250
  manual_seed: 1265
  log_save_dir: "./logs"
  log_save_name: "BetaVAE"
  pic_save_dir: "./scene_divergence_graph"

